# Generated by Django 6.0.7 on 2026-07-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsolicitacao',
            name='variacao',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
