# Generated by Django 6.0.7 on 2026-07-15 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('solicitacao', '0002_alter_itemsolicitacao_variacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsolicitacao',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_solicitados', to='catalogo.produto'),
        ),
    ]
