# Generated by Django 6.0.7 on 2026-07-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='loja/')),
                ('banner_1', models.ImageField(blank=True, null=True, upload_to='loja/banner/')),
                ('banner_2', models.ImageField(blank=True, null=True, upload_to='loja/banner/')),
                ('banner_3', models.ImageField(blank=True, null=True, upload_to='loja/banner/')),
                ('banner_4', models.ImageField(blank=True, null=True, upload_to='loja/banner/')),
                ('telefone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('instagram', models.URLField()),
                ('facebook', models.URLField()),
                ('pix', models.CharField(blank=True, max_length=120)),
                ('cpf', models.CharField(max_length=14)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('cep', models.CharField(max_length=9)),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('cor_primaria', models.CharField(max_length=7)),
                ('cor_secundaria', models.CharField(max_length=7)),
                ('mensagem_whatsapp', models.TextField(default='Olá! Gostaria de fazer um pedido.')),
                ('horario_funcionamento', models.TimeField()),
                ('horario_fechamento', models.TimeField()),
                ('dias_funcionamento', models.CharField(choices=[('S', 'segunda à sexta'), ('SS', 'segunda à sábado')], default='S', max_length=2)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
