# Generated by Django 6.0.7 on 2026-07-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='instagram',
            field=models.URLField(blank=True),
        ),
    ]
