# Generated by Django 6.0.7 on 2026-07-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_loja_facebook_alter_loja_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='loja/logos'),
        ),
    ]
